services:
  readarr-m4b:
    build: .
    container_name: readarr-m4b
    volumes:
      # Mount audiobooks directory (same path as your Readarr container)
      - /mnt/unionfs/Media/Audiobooks:/data/audiobooks
      # Mount temp directory for processing
      - /tmp/readarr-m4b:/tmp/readarr-m4b
      # Mount logs directory for persistence
      - ./logs:/app/logs
    ports:
      - "8080:8080" # Webhook port
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
