# ReadarrM4B Configuration
# Replace the hard-coded paths from your bash scripts

paths:
  # Where Readarr stores your audiobooks (UPDATE THIS PATH)
  audiobooks: "/data/audiobooks"
  
  # Temporary directory for m4b-tool processing
  temp_dir: "/tmp/readarr-m4b"

conversion:
  # m4b-tool settings - audio_codec omitted to use m4b-tool defaults (best quality)
  # audio_codec: "aac"  # Uncomment to override default
  jobs: 4
  use_filenames_as_chapters: true
  no_chapter_reindexing: true
  skip_cover: false
  
  # Wait time before processing (to ensure download is complete)
  stability_wait_seconds: 30
  
  # Clean up original MP3 files after successful conversion
  cleanup_originals: false

logging:
  level: "INFO"  # DEBUG, INFO, WARNING, ERROR
  file: "./readarr-m4b.log"  # Relative path for easier setup

webhook:
  # HTTP server settings for receiving Readarr webhooks
  port: 8080
  host: "0.0.0.0"  # Listen on all interfaces 